### ISSUE TITLE
Where are LazyDense defined in RAVE.jl?

### ISSUE THREAD

**Issue by psanch21** [xukai92/RAVE.jl#1]
Hi xukai92! I am completely new to Julia so I am having some trouble reading the code and identifying the different parts. My question is: Where is the function"LazyDense" in line 53 of the RAVE.jl file defined? I am guessing it is imported using "@reexport using Knet, MLToolkit, Distributions" but I am not sure about it.

On the other hand, could you share some intuition about how to handle the potentially infinite dimensionality in the latent space when using neural networks?

Thank you very much for help and congrats on the nice article!

**Comment by xukai92** [comment]
Hi @psanch21! 

It's defined in the MLToolkit.jl, my helper package: https://github.com/xukai92/MLToolkit.jl/blob/48058e3b15a63e3178af197d5949520f257aa0be/src/neural/layers.jl#L27-L53. 

PS: This repo is supposed to work with `v0.2.0` of MLToolkit.jl.

As you can tell from the code, you expand your weight and bias based on the possible mismatch of input and required output. This is how it's handled with a "dense" layer.

Potentially, you can also use RNN to do the same, but in practice I found RNNs are much harder to train.

**Comment by psanch21** [comment]
Hi! 

Thanks for the quick response! I understand it better now! So just to recep: You define an initial dimension, then during training you expand or compress the weights and biases and at the end of the training you save the model with the latent dimension in the last update. Am I missing something?

Thanks a lot!

**Comment by xukai92** [comment]
Yes you are right. So in fact you don't need to compress. You just don't use them.
