### ISSUE TITLE
The theta_k for non changing encoder and decoder sizes ?

### ISSUE THREAD

**Issue by scakc** [xukai92/RAVE.jl#2]
I want to know if you have a encoder where only last layer size is changing and rest are fixed size, how do you update the network. The update equation is given in terms of kth parameter (psi_k) does that psi_k include the encoder network as it will be present in all the truncation size ?

**Comment by xukai92** [comment]
k is from 1 to the truncation level; see the end of Section 3.4

EDIT: truncated level -> truncation level

**Comment by scakc** [comment]
That part is clear to me sorry for phrasing it in a wrong way. I was asking in a VAE network if  psi_0 and psi_L contains same encoder/decoder parameters (except the layer layer of encoder and first layer of decoder) or you keep separate parameters for each latent representation. Actually i am trying to reproduce this in python since i am unable to run julia it says to add package RRVAE (in jupyter file) which does not exist in package manger. How can i install that package

**Comment by xukai92** [comment]
> That part is clear to me sorry for phrasing it in a wrong way. I was asking in a VAE network if psi_0 and psi_L contains same encoder/decoder parameters (except the layer layer of encoder and first layer of decoder) or you keep separate parameters for each latent representation. 

There are no separate parameters for each latent representation - those layers are shared. 

> Actually i am trying to reproduce this in python since i am unable to run julia it says to add package RRVAE (in jupyter file) which does not exist in package manger. How can i install that package

This is a typo about naming (basically this package was named as RRVAE). I fixed it now and you should do 1) pull this repo 2) do `using Pkg; Pkg.add("path/to/the/repo")`, which would add the package contained in this repo to Julia.

**Comment by scakc** [comment]
Thanks

**Comment by scakc** [comment]
Its running now, but i had to comment out the last two line of RAVE.jl file in src it includes 
include("scrpvae.jl")
export CRPVAE, SCRPVAE, SCRPEncoder

**Comment by xukai92** [comment]
Thanks for letting me know. I will remove them - they were experiemental implementation of CRP models that I didn't have time to tidy up for the paper.

**Comment by xukai92** [comment]
Closed by https://github.com/xukai92/RAVE.jl/commit/a71fcc432079c05b40e28c713d5db6dc0099f796
